WIP: No issue/landkid metrics
atlassian/landkid pull request #103
Opened 2021-04-05 23:09 UTC by luciaquirke

2021-04-14 06:13 UTC, Blasz reviewed
Looks good.

The events seem to be pretty basic for the most part, presumably due to statsd only allowing numeric values.
Since we're able to send richer data structures for the other metrics we want to instrument, I think it would be good to add as much metadata as possible to each event emitted. For example: branch name, target branch, commit etc.
We could then use this metadata to link it with other metadata we collect for branches in CI, such as number of changed packages etc.

If we went down this path, I'm wondering whether we'd want to strictly type the different event types and their payloads or not. It looks like landkid configuration files are javascript. Thoughts @itsjackgardner?

2021-04-15 03:12 UTC, Blasz commented on src/types.ts
> +};
Nice, maybe `sourceBranch` would be worthwhile also in addition to `targetBranch`

2021-04-15 05:49 UTC, Blasz approved these changes
LGTM. Lets wait for @itsjackgardner's review as he's more familiar with the codebase.

2021-04-19 03:23 UTC, merged

2021-04-19 03:30 UTC, itsjackgardner requested changes

2021-04-19 03:30 UTC, itsjackgardner commented on src/lib/Events.ts
> +      eventEmitter.addListener(event, (data: EventData) => {
Could we change the function that's passed into the `.addListener` to be:

```ts
(data?: EventData) => {
  Logger.info(`Emitting event ${event}`, { data });
  listener(data || {});
}
```

That way we can emit events without having to include metadata if there isn't any (e.g. `eventEmitter.emit('STARTUP')`), and it just defaults to an empty object.

2021-04-19 03:30 UTC, itsjackgardner commented on src/lib/Runner.ts
> -  };
I just realised that I was wrong about not needing this function anymore, will need to replace `landRequestStatus.date.getTime()` with what we had before, sorry about that.